"""Add Conversations-Rep-Requests-Link

Revision ID: 8d27c14cb57c
Revises: b75cd5fae31f
Create Date: 2026-03-19 14:15:21.716956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d27c14cb57c'
down_revision: Union[str, Sequence[str], None] = 'b75cd5fae31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_requests', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('report_requests_user_id_fkey'), 'report_requests', type_='foreignkey')
    op.create_foreign_key(None, 'report_requests', 'conversations', ['conversation_id'], ['id'])
    op.drop_column('report_requests', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_requests', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'report_requests', type_='foreignkey')
    op.create_foreign_key(op.f('report_requests_user_id_fkey'), 'report_requests', 'users', ['user_id'], ['id'])
    op.drop_column('report_requests', 'conversation_id')
    # ### end Alembic commands ###
